import { Equipo, Estadio, WeatherOption } from './types';

export const EQUIPOS: Equipo[] = [
  // CONMEBOL
  { name: "Argentina", flag: "🇦🇷", grupo: "J", conf: "CONMEBOL", ranking: 1, 
    climaFav: ["frío", "templado"], climaAfecta: ["calor extremo", "humedad alta"],
    golesXP: 2.1, estiloGol: "Alto pressing ofensivo, Messi (34) + Álvarez.",
    handicapBias: -0.5, climaData: "Acostumbrada a climas templados-fríos de Buenos Aires y Córdoba. El calor extremo por encima de 35°C reduce su intensidad ofensiva notablemente." },
  { name: "Brasil", flag: "🇧🇷", grupo: "C", conf: "CONMEBOL", ranking: 5,
    climaFav: ["calor", "húmedo", "lluvia leve"], climaAfecta: ["frío extremo", "viento fuerte"],
    golesXP: 2.3, estiloGol: "Toque corto, transiciones rápidas.",
    handicapBias: -0.75, climaData: "Adaptada al calor y humedad tropical. Bajo rendimiento histórico en climas fríos (+8°C o menos), donde pierde explosividad y velocidad." },
  { name: "Colombia", flag: "🇨🇴", grupo: "K", conf: "CONMEBOL", ranking: 9,
    climaFav: ["templado", "lluvia moderada"], climaAfecta: ["calor seco", "viento fuerte"],
    golesXP: 1.9, estiloGol: "Contragolpe veloz, James Rodríguez creador.",
    handicapBias: -0.25, climaData: "Acostumbrada a climas de altitud media (Bogotá, Medellín). Rinde bien en temperaturas entre 15–25°C. El calor seco de ciudades como Dallas puede afectarla." },
  { name: "Ecuador", flag: "🇪🇨", grupo: "E", conf: "CONMEBOL", ranking: 22,
    climaFav: ["templado", "altitude"], climaAfecta: ["calor extremo"],
    golesXP: 1.7, estiloGol: "Bloque medio, contragolpe.",
    handicapBias: 0, climaData: "Habituada a la altitud de Quito (2850m). Juega en Miami, Kansas City y Nueva York, ciudades sin altitud, lo que reduce su ventaja adaptativa." },
  { name: "Paraguay", flag: "🇵🇾", grupo: "D", conf: "CONMEBOL", ranking: 29,
    climaFav: ["calor húmedo", "templado"], climaAfecta: ["frío"],
    golesXP: 1.6, estiloGol: "Defensivo sólido, pelota parada.",
    handicapBias: 0.25, climaData: "Paraguayos adaptados al calor subtropical de Asunción. En ciudades del norte de EEUU con frío (Vancouver, Seattle), su rendimiento físico puede bajar." },
  { name: "Uruguay", flag: "🇺🇾", grupo: "H", conf: "CONMEBOL", ranking: 12,
    climaFav: ["templado", "frío"], climaAfecta: ["calor extremo", "humedad extrema"],
    golesXP: 1.8, estiloGol: "Presión alta, doble pivote, Núñez / Olivera.",
    handicapBias: -0.25, climaData: "Históricamente potente en climas templados y fríos. El calor de ciudades como Miami puede afectar su intensidad física. 2 Copas del Mundo ganadas (1930, 1950)." },

  // UEFA
  { name: "Alemania", flag: "🇩🇪", grupo: "E", conf: "UEFA", ranking: 16,
    climaFav: ["frío", "templado", "lluvia"], climaAfecta: ["calor extremo"],
    golesXP: 2.4, estiloGol: "Pressing alto, transición rápida, Havertz / Musiala.",
    handicapBias: -0.5, climaData: "Alemania es una de las selecciones más efectivas en climas fríos y lluviosos. 4 Copas del Mundo. En calor extremo (+33°C) pierde presión en las últimas fases." },
  { name: "Austria", flag: "🇦🇹", grupo: "J", conf: "UEFA", ranking: 19,
    climaFav: ["frío", "templado"], climaAfecta: ["calor", "humedad alta"],
    golesXP: 1.8, estiloGol: "Presión agresiva, Sabitzer liderazgo.",
    handicapBias: 0.25, climaData: "Acostumbrada a climas alpinos fríos. El calor de Texas o Miami puede reducir su capacidad de presión intensa." },
  { name: "Bélgica", flag: "🇧🇪", grupo: "G", conf: "UEFA", ranking: 13,
    climaFav: ["templado", "lluvia"], climaAfecta: ["calor extremo"],
    golesXP: 2.1, estiloGol: "Posesión técnica, De Bruyne como motor.",
    handicapBias: -0.5, climaData: "Generación nueva postGolden Generation. Sólida en climas europeos. En calor extremo algunos jugadores muestran fatiga prematura en el 2do tiempo." },
  { name: "Bosnia y Herzegovina", flag: "🇧🇦", grupo: "L", conf: "UEFA", ranking: 65,
    climaFav: ["templado", "frío"], climaAfecta: ["calor extremo", "humedad"],
    golesXP: 1.6, estiloGol: "Juego directo, Džeko generación siguiente.",
    handicapBias: 0.5, climaData: "Sin experiencia mundialista previa en calor. Primera Copa del Mundo (después de Brasil 2014). En climas húmedos y cálidos su rendimiento físico decrece." },
  { name: "Croacia", flag: "🇭🇷", grupo: "L", conf: "UEFA", ranking: 10,
    climaFav: ["templado", "calor moderado"], climaAfecta: ["frío extremo"],
    golesXP: 1.9, estiloGol: "Posesión y control del centro. Kovačić / Modrić (experiencia).",
    handicapBias: -0.25, climaData: "Finalista en 2018 y 3ro en 2022. Adaptada a diversos climas. El calor mediterráneo es familiar. Croacia históricamente rinde bien en variedad climática." },
  { name: "España", flag: "🇪🇸", grupo: "H", conf: "UEFA", ranking: 4,
    climaFav: ["calor moderado", "templado"], climaAfecta: ["frío extremo", "lluvia fuerte"],
    golesXP: 2.2, estiloGol: "Tiki-taka evolucionado, posesión-presión. Yamal/Pedri/Morata.",
    handicapBias: -0.75, climaData: "Campeona 2010. Adaptada a climas cálidos y secos. En lluvia intensa pierde algo de precisión técnica. Su juego de toque sufre en canchas encharcadas." },
  { name: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", grupo: "C", conf: "UEFA", ranking: 35,
    climaFav: ["frío", "lluvia"], climaAfecta: ["calor", "humedad"],
    golesXP: 1.5, estiloGol: "Directo, juego aéreo, físico.",
    handicapBias: 0.75, climaData: "Habituada al frío y lluvia de las Islas Británicas. En calor extremo su juego de pressing pierde intensidad significativamente." },
  { name: "Francia", flag: "🇫🇷", grupo: "I", conf: "UEFA", ranking: 2,
    climaFav: ["templado", "calor moderado"], climaAfecta: ["frío extremo"],
    golesXP: 2.3, estiloGol: "Transición ultrarrápida, velocidad extrema. Mbappé.",
    handicapBias: -0.75, climaData: "Campeona 2018, finalista 2022. Adaptable a diversos climas. Mbappé pierde algo de velocidad explosiva en frío extremo. En general muy adaptable." },
  { name: "Noruega", flag: "🇳🇴", grupo: "I", conf: "UEFA", ranking: 15,
    climaFav: ["frío", "lluvia"], climaAfecta: ["calor extremo", "humedad tropical"],
    golesXP: 2.2, estiloGol: "Directo a Haaland, pressing alto.",
    handicapBias: -0.25, climaData: "Haaland y compañía acostumbrados al frío escandinavo. En calor extremo (Miami, Houston, 35°C+) pueden sufrir fatiga prematura. Debut mundialista histórico." },
  { name: "Países Bajos", flag: "🇳🇱", grupo: "F", conf: "UEFA", ranking: 7,
    climaFav: ["templado", "lluvia"], climaAfecta: ["calor extremo"],
    golesXP: 2.1, estiloGol: "Presión alta, posesión, van Dijk / Gakpo / Xavi Simons.",
    handicapBias: -0.5, climaData: "Finalista en 2010. Potente en climas europeos. En calor extremo algunos jugadores tienden a especular más y bajar el ritmo de presión." },
  { name: "Portugal", flag: "🇵🇹", grupo: "K", conf: "UEFA", ranking: 6,
    climaFav: ["calor moderado", "templado"], climaAfecta: ["frío extremo"],
    golesXP: 2.1, estiloGol: "Individual de alto nivel, Ronaldo / Bruno / Leão.",
    handicapBias: -0.5, climaData: "Portugal se adapta bien al calor mediterráneo. Ronaldo (41) puede sufrir en calor extremo. Hay una generación intermedia (Rafael Leão) que rinde mejor en climas moderados." },
  { name: "República Checa", flag: "🇨🇿", grupo: "A", conf: "UEFA", ranking: 36,
    climaFav: ["frío", "templado"], climaAfecta: ["calor", "humedad"],
    golesXP: 1.6, estiloGol: "Bloque medio, contraataque. Schick referencia.",
    handicapBias: 0.5, climaData: "No acostumbrada a calor extremo. El formato en México (CDMX) puede ser favorable por altitud similar a Europa central, pero el calor de Houston les afecta." },
  { name: "Suecia", flag: "🇸🇪", grupo: "F", conf: "UEFA", ranking: 24,
    climaFav: ["frío", "lluvia"], climaAfecta: ["calor extremo", "humedad"],
    golesXP: 1.7, estiloGol: "Físico, aéreo, directo.",
    handicapBias: 0.25, climaData: "Típicamente escandinava, efectiva en climas fríos. En calor extremo (Texas, Miami en verano) puede perder efectividad física en el 2do tiempo." },
  { name: "Suiza", flag: "🇨🇭", grupo: "—", conf: "UEFA", ranking: 18,
    climaFav: ["templado", "frío"], climaAfecta: ["calor extremo"],
    golesXP: 1.7, estiloGol: "Organizado, presión media, Shaqiri experiencia.",
    handicapBias: 0.25, climaData: "Adaptable, pero históricamente mejor en climas europeos. No tienen experiencia en calor tropical. Muy disciplinados tácticamente en cualquier clima." },
  { name: "Turquía", flag: "🇹🇷", grupo: "D", conf: "UEFA", ranking: 27,
    climaFav: ["calor moderado", "templado"], climaAfecta: ["frío extremo", "lluvia fuerte"],
    golesXP: 1.8, estiloGol: "Físico, intenso, Calhanoglu / Yazici.",
    handicapBias: 0.25, climaData: "Turquía se adaptó al calor de Qatar 2022. Rinden bien entre 20–30°C. El frío extremo de Vancouver o Seattle puede afectar su intensidad característica." },
  { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", grupo: "L", conf: "UEFA", ranking: 3,
    climaFav: ["templado", "lluvia"], climaAfecta: ["calor extremo"],
    golesXP: 2.0, estiloGol: "Directo con presión, Bellingham / Saka / Kane.",
    handicapBias: -0.5, climaData: "Kane puede sufrir en calor extremo. Históricamente mal en penaltis bajo presión extrema. En climas templados-lluviosos (típico inglés) son muy sólidos." },

  // CAF
  { name: "Argelia", flag: "🇩🇿", grupo: "J", conf: "CAF", ranking: 50,
    climaFav: ["calor seco", "templado"], climaAfecta: ["frío", "humedad extrema"],
    golesXP: 1.5, estiloGol: "Organizado, transición.",
    handicapBias: 0.5, climaData: "Adaptada al calor del desierto. En climas fríos y húmedos pierde su ritmo característico. El calor de las sedes del sur de EEUU les favorece." },
  { name: "Cabo Verde", flag: "🇨🇻", grupo: "H", conf: "CAF", ranking: 77,
    climaFav: ["calor", "templado cálido"], climaAfecta: ["frío", "altitud alta"],
    golesXP: 1.3, estiloGol: "Organizado, defensivo. Primera Copa del Mundo.",
    handicapBias: 1.0, climaData: "Isleños del Atlántico acostumbrados a calor húmedo oceánico. Los climas fríos del norte del continente (Vancouver, Seattle, Boston) son desfavorables para ellos." },
  { name: "Costa de Marfil", flag: "🇨🇮", grupo: "E", conf: "CAF", ranking: 48,
    climaFav: ["calor húmedo"], climaAfecta: ["frío", "altitud"],
    golesXP: 1.6, estiloGol: "Físico y técnico, transiciones.",
    handicapBias: 0.5, climaData: "Habituados al clima tropical del Golfo de Guinea. En climas fríos pierden velocidad física. El calor del sur de EEUU es su hábitat natural." },
  { name: "Egipto", flag: "🇪🇬", grupo: "G", conf: "CAF", ranking: 31,
    climaFav: ["calor seco"], climaAfecta: ["frío", "humedad extrema"],
    golesXP: 1.6, estiloGol: "Mo Salah dependiente, defensivo compacto.",
    handicapBias: 0.25, climaData: "Adaptados al calor seco mediterráneo y desértico. Mo Salah sabe manejar el calor extremo. En climas fríos o muy húmedos pierden intensidad." },
  { name: "Ghana", flag: "🇬🇭", grupo: "L", conf: "CAF", ranking: 60,
    climaFav: ["calor", "humedad"], climaAfecta: ["frío extremo"],
    golesXP: 1.5, estiloGol: "Físico, directo, rápido.",
    handicapBias: 0.5, climaData: "Acostumbrados al calor tropical. Los climas fríos del norte (Vancouver, Toronto) pueden afectar su rendimiento físico habitual." },
  { name: "Marruecos", flag: "🇲🇦", grupo: "C", conf: "CAF", ranking: 14,
    climaFav: ["templado", "calor seco"], climaAfecta: ["frío extremo", "lluvia fuerte"],
    golesXP: 1.7, estiloGol: "Bloque defensivo sólido, transición, Hakimi.",
    handicapBias: 0, climaData: "4to lugar Qatar 2022. Adaptados a climas cálidos y secos del Mediterráneo. En frío extremo su bloque defensivo se mantiene, pero el ritmo ofensivo baja." },
  { name: "RD Congo", flag: "🇨🇩", grupo: "K", conf: "CAF", ranking: 53,
    climaFav: ["calor húmedo"], climaAfecta: ["frío", "altitud baja seca"],
    golesXP: 1.4, estiloGol: "Físico, rápido, técnico individual.",
    handicapBias: 0.75, climaData: "Ecuatorial tropical. Rinden en calor húmedo. En frío extremo puede notarse dificultad de adaptación y menor intensidad en pressing." },
  { name: "Senegal", flag: "🇸🇳", grupo: "I", conf: "CAF", ranking: 20,
    climaFav: ["calor", "humedad"], climaAfecta: ["frío extremo"],
    golesXP: 1.7, estiloGol: "Físico y técnico, Sadio Mané / Diatta.",
    handicapBias: 0.25, climaData: "Campeón africano 2022. Habituados al calor atlántico. En climas fríos del norte pierden algo de explosive power. Muy bien organizados tácticamente en diversas condiciones." },
  { name: "Sudáfrica", flag: "🇿🇦", grupo: "A", conf: "CAF", ranking: 58,
    climaFav: ["templado", "calor moderado"], climaAfecta: ["humedad extrema", "frío"],
    golesXP: 1.4, estiloGol: "Físico, directo. Primera Copa del Mundo fuera del continente africano.",
    handicapBias: 0.75, climaData: "Clima del sur de África (Johannesburgo, Ciudad del Cabo) es templado. En calor extremo húmedo de Miami o Houston puede bajar el rendimiento." },
  { name: "Túnez", flag: "🇹🇳", grupo: "F", conf: "CAF", ranking: 30,
    climaFav: ["calor seco", "templado"], climaAfecta: ["frío", "lluvia fuerte"],
    golesXP: 1.4, estiloGol: "Organizado, defensivo, contragolpe.",
    handicapBias: 0.5, climaData: "Adaptados al calor mediterráneo. En frío extremo (Vancouver, Seattle en junio) pueden no rendir a su nivel habitual. Lluvia fuerte afecta su juego técnico." },

  // AFC
  { name: "Arabia Saudita", flag: "🇸🇦", grupo: "H", conf: "AFC", ranking: 57,
    climaFav: ["calor seco extremo"], climaAfecta: ["frío", "lluvia"],
    golesXP: 1.5, estiloGol: "Directo, organizado, sorpresa de Qatar 2022.",
    handicapBias: 0.5, climaData: "Acostumbrados a calor extremo desértico. En frío extremo con lluvia su rendimiento cae notablemente. El calor de Dallas o Houston es favorable." },
  { name: "Australia", flag: "🇦🇺", grupo: "D", conf: "AFC", ranking: 23,
    climaFav: ["templado"], climaAfecta: ["calor extremo", "altitud"],
    golesXP: 1.5, estiloGol: "Físico, aéreo, organizado. Socceroos.",
    handicapBias: 0.5, climaData: "Diverse climate at home. Habituados a varied conditions. Rinden bien en climas templados similares a los de las grandes ciudades australianas." },
  { name: "Catar", flag: "🇶🇦", grupo: "—", conf: "AFC", ranking: 71,
    climaFav: ["calor extremo"], climaAfecta: ["frío", "lluvia", "humedad alta"],
    golesXP: 1.2, estiloGol: "Tiki-taka imitado, débil mundialista.",
    handicapBias: 1.0, climaData: "Anfitriones de 2022, eliminados en fase de grupos. Adaptados al calor del Golfo Pérsico. El frío y la lluvia de ciudades norteñas son desfavorables." },
  { name: "Corea del Sur", flag: "🇰🇷", grupo: "A", conf: "AFC", ranking: 24,
    climaFav: ["templado", "frío"], climaAfecta: ["calor extremo", "humedad"],
    golesXP: 1.5, estiloGol: "Pressing intenso, físico, Son Heung-min.",
    handicapBias: 0.25, climaData: "Habituados al frío coreano y la intensidad física. En calor extremo (+35°C) su pressing puede bajar de nivel. Son rinde mejor en climas frescos." },
  { name: "Irak", flag: "🇮🇶", grupo: "I", conf: "AFC", ranking: 70,
    climaFav: ["calor seco extremo"], climaAfecta: ["frío", "lluvia fuerte"],
    golesXP: 1.3, estiloGol: "Organizado defensivo. Vuelven al Mundial 40 años después.",
    handicapBias: 1.0, climaData: "Acostumbrados al calor extremo de Bagdad y Basra. El frío y la lluvia de ciudades norteñas son desfavorables. Primera Copa del Mundo desde México 1986." },
  { name: "Irán", flag: "🇮🇷", grupo: "G", conf: "AFC", ranking: 25,
    climaFav: ["calor seco", "templado"], climaAfecta: ["frío extremo", "humedad"],
    golesXP: 1.4, estiloGol: "Defensivo, bloque bajo, contragolpe.",
    handicapBias: 0.5, climaData: "Adaptados al clima continental de Irán (calor seco). En frío extremo con lluvia pierden algo de efectividad en su juego de presión media." },
  { name: "Japón", flag: "🇯🇵", grupo: "F", conf: "AFC", ranking: 17,
    climaFav: ["templado", "lluvia moderada"], climaAfecta: ["calor extremo seco"],
    golesXP: 1.7, estiloGol: "Alta intensidad, pressing, técnica. Doan/Kubo.",
    handicapBias: 0.25, climaData: "Habituados al clima húmedo japonés. En calor seco de Texas o las planicies pueden perder intensidad. Sorpresa de 2022 (venció a Alemania y España)." },
  { name: "Jordania", flag: "🇯🇴", grupo: "J", conf: "AFC", ranking: 68,
    climaFav: ["calor seco"], climaAfecta: ["frío", "humedad extrema"],
    golesXP: 1.3, estiloGol: "Organizado, defensivo. Segunda Copa del Mundo.",
    handicapBias: 0.75, climaData: "Habituados al clima desértico seco. En frío extremo y lluvia intensa pierden efectividad. Primera aparición mundialista de la historia." },
  { name: "Uzbekistán", flag: "🇺🇿", grupo: "K", conf: "AFC", ranking: 62,
    climaFav: ["templado", "calor moderado"], climaAfecta: ["humedad extrema", "frío extremo"],
    golesXP: 1.3, estiloGol: "Técnico y físico. Debut mundialista histórico.",
    handicapBias: 0.75, climaData: "Clima continental de Asia Central (calor seco de verano). Adaptados a variedad, pero el calor húmedo de Miami o la altitud de Ciudad de México son nuevos para ellos." },

  // CONCACAF
  { name: "Canadá", flag: "🇨🇦", grupo: "B", conf: "CONCACAF", ranking: 38,
    climaFav: ["frío", "lluvia", "templado"], climaAfecta: ["calor extremo"],
    golesXP: 1.7, estiloGol: "Físico, atlético, Davies como referencia.",
    handicapBias: 0.25, climaData: "Habituados al frío canadiense. En calor extremo de Miami o Dallas pueden sentir fatiga prematura. Como anfitriones, la energía local compensa." },
  { name: "Curazao", flag: "🇨🇼", grupo: "E", conf: "CONCACAF", ranking: 83,
    climaFav: ["calor húmedo", "tropical"], climaAfecta: ["frío", "altitud"],
    golesXP: 1.2, estiloGol: "Caribeño, técnico, físico. Primera Copa del Mundo.",
    handicapBias: 1.5, climaData: "Isleños del Caribe, adaptados a calor húmedo. En frío extremo y altitud de Ciudad de México pueden tener problemas. Nación más pequeña en la historia de los Mundiales." },
  { name: "Estados Unidos", flag: "🇺🇸", grupo: "D", conf: "CONCACAF", ranking: 11,
    climaFav: ["templado", "variado"], climaAfecta: ["nada específico"],
    golesXP: 1.8, estiloGol: "Físico, atlético, presión alta. Pulisic / Reyna.",
    handicapBias: 0, climaData: "Como anfitriones, juegan en sus propios estadios. Conocen todos los microclimas de sus sedes. En casa tienen ventaja adaptativa significativa." },
  { name: "Haití", flag: "🇭🇹", grupo: "C", conf: "CONCACAF", ranking: 99,
    climaFav: ["calor húmedo"], climaAfecta: ["frío", "lluvia fuerte", "viento"],
    golesXP: 1.2, estiloGol: "Técnico, caribeño, directo.",
    handicapBias: 1.5, climaData: "Habituados al calor tropical caribeño. En frío extremo o lluvia fuerte pueden sufrir. El calor de Miami les favorece, mientras que el frío de Vancouver es una desventaja." },
  { name: "México", flag: "🇲🇽", grupo: "A", conf: "CONCACAF", ranking: 15,
    climaFav: ["templado", "altitud", "calor moderado"], climaAfecta: ["frío extremo", "humedad alta"],
    golesXP: 1.9, estiloGol: "Técnico y posesión, equipo anfitrión. Lozano / Jiménez.",
    handicapBias: -0.25, climaData: "Anfitriones. Perfectamente adaptados a la altitud de CDMX (2240m) and el calor de Guadalajara y Monterrey. La energía local es un factor determinante." },
  { name: "Panamá", flag: "🇵🇦", grupo: "L", conf: "CONCACAF", ranking: 87,
    climaFav: ["calor húmedo tropical"], climaAfecta: ["frío", "lluvia fuerte", "viento"],
    golesXP: 1.2, estiloGol: "Defensivo, físico, organizado.",
    handicapBias: 1.0, climaData: "Habituados al calor húmedo tropical. El frío de ciudades del norte de EEUU o Canadá puede afectar su rendimiento físico. El calor de Miami o Dallas les favorece." },

  // OFC
  { name: "Nueva Zelanda", flag: "🇳🇿", grupo: "G", conf: "OFC", ranking: 97,
    climaFav: ["templado", "lluvia"], climaAfecta: ["calor extremo"],
    golesXP: 1.1, estiloGol: "Físico, aéreo. All Whites.",
    handicapBias: 1.5, climaData: "Adaptados al clima marítimo templado. En calor extremo (Texas, Miami en junio-julio) pueden perder efectividad física. Primera Copa del Mundo en muchos años." },
];

export const ESTADIOS: Estadio[] = [
  // MÉXICO
  { name: "Estadio Azteca (Ciudad de México)", ciudad: "Ciudad de México, MX", pais: "México",
    cap: 87500, temp: "15–25°C", tipo: "Cubierto Parcial (marquesina)", altitud: "2240m (Alta)",
    humedad: "Media-Baja", historia: "Único estadio en albergar 3 Copas del Mundo (1970, 1986, 2026). Sede del gol de la mano de Maradona y el Gol del Siglo. Nombre FIFA: Mexico City Stadium. Inauguró el torneo el 11-Jun.",
    flag: "🇲🇽", partidos: "5 partidos: Partido inaugural + 3 fase de grupos + Ronda de 32" },
  { name: "Estadio Akron (Guadalajara)", ciudad: "Zapopan (Guadalajara), MX", pais: "México",
    cap: 48000, temp: "18–28°C", tipo: "Cubierto Parcial", altitud: "1560m (Media-Alta)",
    humedad: "Media", historia: "Casa de Chivas de Guadalajara. Nombre FIFA: Guadalajara Stadium. Zona metropolitana de Guadalajara, clima primaveral durante el torneo.",
    flag: "🇲🇽", partidos: "4 partidos fase de grupos" },
  { name: "Estadio BBVA (Monterrey)", ciudad: "Guadalupe (Monterrey), MX", pais: "México",
    cap: 53500, temp: "22–38°C", tipo: "Cubierto Parcial", altitud: "538m (Baja)",
    humedad: "Media-Alta", historia: "Casa de Rayados de Monterrey. Nombre FIFA: Monterrey Stadium. Inaugurado en 2015. Zona norte de México, calor intenso en verano.",
    flag: "🇲🇽", partidos: "4 partidos: 3 fase de grupos + Ronda de 32" },

  // ESTADOS UNIDOS
  { name: "AT&T Stadium (Dallas)", ciudad: "Arlington (Dallas), USA", pais: "EEUU",
    cap: 92967, temp: "28–42°C", tipo: "Techo retráctil (clima controlado)", altitud: "195m (Baja)",
    humedad: "Media-Baja", historia: "El estadio más grande del torneo (92,967). Casa de Dallas Cowboys NFL. Nombre FIFA: Dallas Stadium. Renovado con $350M. Récord: 9 partidos, más que cualquier otra sede, incluyendo Semifinal.",
    flag: "🇺🇸", partidos: "9 partidos: fase de grupos + Ronda 32 (×2) + Octavos + Semifinal (14-Jul)" },
  { name: "MetLife Stadium (Nueva York/Nueva Jersey)", ciudad: "East Rutherford (Nueva York), USA", pais: "EEUU",
    cap: 82500, temp: "18–30°C", tipo: "Abierto", altitud: "5m (Muy Baja)",
    humedad: "Alta", historia: "SEDE DE LA GRAN FINAL (19-Jul). Casa de NY Giants y Jets. Nombre FIFA: New York New Jersey Stadium. Renovado para el Mundial: césped natural, ampliación de campo a 105×68m.",
    flag: "🇺🇸", partidos: "8 partidos: fase de grupos + Ronda 32 + Octavos + Gran Final (19-Jul)" },
  { name: "Arrowhead Stadium (Kansas City)", ciudad: "Kansas City, USA", pais: "EEUU",
    cap: 76640, temp: "22–35°C", tipo: "Abierto", altitud: "277m (Baja)",
    humedad: "Alta", historia: "El estadio más RUIDOSO del mundo (Guinness: 142.2 dB). Casa de Kansas City Chiefs. Nombre FIFA: Kansas City Stadium. Inaugurado en 1972, el más antiguo del torneo.",
    flag: "🇺🇸", partidos: "6 partidos: fase de grupos + eliminatorias" },
  { name: "NRG Stadium (Houston)", ciudad: "Houston, USA", pais: "EEUU",
    cap: 72220, temp: "30–40°C", tipo: "Techo retráctil (clima controlado)", altitud: "15m (Muy Baja)",
    humedad: "Muy Alta (subtropical)", historia: "Primer estadio NFL con techo retráctil. Nombre FIFA: Houston Stadium. Calor tropical extremo en verano. Sede de partidos de Portugal, Alemania y Países Bajos.",
    flag: "🇺🇸", partidos: "7 partidos: fase de grupos + Ronda 32 + Octavos" },
  { name: "Mercedes-Benz Stadium (Atlanta)", ciudad: "Atlanta, USA", pais: "EEUU",
    cap: 71000, temp: "25–35°C", tipo: "Techo retráctil (cierre total)", altitud: "320m (Baja)",
    humedad: "Alta", historia: "Casa de Atlanta United y Falcons. Nombre FIFA: Atlanta Stadium. Renovación especial: césped híbrido de Kentucky bluegrass plantado en Colorado. Sede de una Semifinal.",
    flag: "🇺🇸", partidos: "8 partidos: fase de grupos + Ronda 32 + Octavos + Semifinal (15-Jul)" },
  { name: "Levi's Stadium (San Francisco)", ciudad: "Santa Clara (San Francisco), USA", pais: "EEUU",
    cap: 70909, temp: "14–24°C", tipo: "Abierto", altitud: "15m (Baja)",
    humedad: "Media-Baja", historia: "Casa de San Francisco 49ers. Nombre FIFA: San Francisco Bay Area Stadium. Certificación LEED Gold con paneles solares. Sede del Super Bowl LX (feb 2026).",
    flag: "🇺🇸", partidos: "6 partidos: fase de grupos + Ronda de 32" },
  { name: "SoFi Stadium (Los Ángeles)", ciudad: "Inglewood (Los Ángeles), USA", pais: "EEUU",
    cap: 70240, temp: "20–30°C", tipo: "Cubierto translúcido (ETFE)", altitud: "60m (Baja)",
    humedad: "Baja-Media", historia: "El estadio más caro del mundo ($5.5 mil millones). Casa de LA Rams y Chargers. Nombre FIFA: Los Angeles Stadium. Sede del partido inaugural de EEUU vs Paraguay.",
    flag: "🇺🇸", partidos: "8 partidos: fase de grupos + Ronda 32 (×2) + Cuartos de Final (10-Jul)" },
  { name: "Lincoln Financial Field (Filadelfia)", ciudad: "Filadelfia, USA", pais: "EEUU",
    cap: 69328, temp: "22–33°C", tipo: "Abierto", altitud: "9m (Muy Baja)",
    humedad: "Alta", historia: "Casa de Philadelphia Eagles. Nombre FIFA: Philadelphia Stadium. Clima cálido y húmedo en verano. Uno de los estadios con más historia en la costa este.",
    flag: "🇺🇸", partidos: "6 partidos: fase de grupos + eliminatorias" },
  { name: "Lumen Field (Seattle)", ciudad: "Seattle, USA", pais: "EEUU",
    cap: 68740, temp: "12–22°C", tipo: "Abierto (marquesina parcial)", altitud: "6m (Muy Baja)",
    humedad: "Alta (lluvia frecuente)", historia: "Casa de Seattle Seahawks. Nombre FIFA: Seattle Stadium. Ciudad más lluviosa del torneo. Clima fresco propio del noroeste del Pacífico.",
    flag: "🇺🇸", partidos: "6 partidos: fase de grupos + eliminatorias" },
  { name: "Hard Rock Stadium (Miami)", ciudad: "Miami Gardens (Miami), USA", pais: "EEUU",
    cap: 65000, temp: "28–38°C", tipo: "Marquesina (techo fijo parcial)", altitud: "1m (Muy Baja)",
    humedad: "Muy Alta (tropical)", historia: "Casa de Miami Dolphins. Nombre FIFA: Miami Stadium. SEDE DEL TERCER LUGAR (3er-4to puesto). Calor tropical extremo, la sede más cálida y húmeda del torneo.",
    flag: "🇺🇸", partidos: "7 partidos: fase de grupos + Ronda 32 + Octavos + 3er Puesto" },
  { name: "Gillette Stadium (Boston)", ciudad: "Foxborough (Boston), USA", pais: "EEUU",
    cap: 64628, temp: "17–27°C", tipo: "Abierto", altitud: "30m (Muy Baja)",
    humedad: "Alta", historia: "Casa de New England Patriots. Nombre FIFA: Boston Stadium. Clima templado del noreste, uno de los más frescos entre las sedes estadounidenses.",
    flag: "🇺🇸", partidos: "7 partidos: fase de grupos + eliminatorias" },

  // CANADÁ
  { name: "BC Place (Vancouver)", ciudad: "Vancouver, Canadá", pais: "Canadá",
    cap: 54500, temp: "13–22°C", tipo: "Techo retráctil (inflable)", altitud: "4m (Muy Baja)",
    humedad: "Alta (lluvia frecuente)", historia: "Sede de la final femenina del Mundial 2015. Nombre FIFA: BC Place Vancouver. Techo inflable único en el mundo. Clima fresco del Pacífico, la sede más fría del torneo.",
    flag: "🇨🇦", partidos: "7 partidos: fase de grupos + Ronda de 32" },
  { name: "BMO Field (Toronto)", ciudad: "Toronto, Canadá", pais: "Canadá",
    cap: 45736, temp: "18–28°C", tipo: "Abierto", altitud: "76m (Muy Baja)",
    humedad: "Alta", historia: "El estadio más pequeño del torneo (45,736). Casa del Toronto FC. Nombre FIFA: Toronto Stadium. Sede del debut de Canadá como co-anfitrión del Mundial.",
    flag: "🇨🇦", partidos: "6 partidos: fase de grupos + eliminatorias" },
];

export const WEATHER_OPTIONS: WeatherOption[] = [
  { id: "soleado",      icon: "☀️",  label: "Soleado",        temp: [25, 35], hum: [20, 45], viento: [5, 15], golesAdj: 0,     handicapAdj: 0 },
  { id: "calor",        icon: "🥵",  label: "Calor Extremo",  temp: [35, 42], hum: [30, 60], viento: [5, 20], golesAdj: -0.15, handicapAdj: 0.05 },
  { id: "templado",     icon: "🌤️", label: "Templado",       temp: [18, 25], hum: [45, 65], viento: [10, 20], golesAdj: 0.12, handicapAdj: -0.05 },
  { id: "nublado",      icon: "⛅",  label: "Nublado",        temp: [15, 22], hum: [55, 75], viento: [15, 25], golesAdj: 0.08, handicapAdj: 0 },
  { id: "lluvia_leve",  icon: "🌦️", label: "Lluvia Leve",    temp: [14, 20], hum: [70, 85], viento: [15, 25], golesAdj: 0.05, handicapAdj: 0.05 },
  { id: "lluvia_mod",   icon: "🌧️", label: "Lluvia Moderada",temp: [12, 18], hum: [80, 90], viento: [20, 35], golesAdj: -0.1,  handicapAdj: 0.1 },
  { id: "lluvia_int",   icon: "⛈️", label: "Lluvia Intensa", temp: [10, 16], hum: [85, 95], viento: [30, 50], golesAdj: -0.25, handicapAdj: 0.2 },
  { id: "frio",         icon: "🥶",  label: "Frío",           temp: [5, 14],  hum: [50, 75], viento: [20, 40], golesAdj: -0.08, handicapAdj: 0.08 },
  { id: "viento",       icon: "💨",  label: "Viento Fuerte",  temp: [15, 25], hum: [40, 60], viento: [40, 70], golesAdj: -0.2,  handicapAdj: 0.15 },
  { id: "niebla",       icon: "🌫️", label: "Niebla",         temp: [8, 15],  hum: [85, 95], viento: [0, 10],  golesAdj: -0.05, handicapAdj: 0.05 },
];

export const HISTORICO = {
  goles: [
    { mundial: "Uruguay 1930", partidos: 18, goles: 70, prom: 3.89, plus25pct: 61 },
    { mundial: "Italia 1934", partidos: 17, goles: 70, prom: 4.12, plus25pct: 65 },
    { mundial: "Francia 1938", partidos: 18, goles: 84, prom: 4.67, plus25pct: 72 },
    { mundial: "Brasil 1950", partidos: 22, goles: 88, prom: 4.00, plus25pct: 68 },
    { mundial: "Suiza 1954", partidos: 26, goles: 140, prom: 5.38, plus25pct: 81 },
    { mundial: "Suecia 1958", partidos: 35, goles: 126, prom: 3.60, plus25pct: 63 },
    { mundial: "Chile 1962", partidos: 32, goles: 89, prom: 2.78, plus25pct: 44 },
    { mundial: "Inglaterra 1966", partidos: 32, goles: 89, prom: 2.78, plus25pct: 44 },
    { mundial: "México 1970", partidos: 32, goles: 95, prom: 2.97, plus25pct: 47 },
    { mundial: "Alemania 1974", partidos: 38, goles: 97, prom: 2.55, plus25pct: 37 },
    { mundial: "Argentina 1978", partidos: 38, goles: 102, prom: 2.68, plus25pct: 42 },
    { mundial: "España 1982", partidos: 52, goles: 146, prom: 2.81, plus25pct: 46 },
    { mundial: "México 1986", partidos: 52, goles: 132, prom: 2.54, plus25pct: 40 },
    { mundial: "Italia 1990", partidos: 52, goles: 115, prom: 2.21, plus25pct: 33 },
    { mundial: "EEUU 1994", partidos: 52, goles: 141, prom: 2.71, plus25pct: 44 },
    { mundial: "Francia 1998", partidos: 64, goles: 171, prom: 2.67, plus25pct: 43 },
    { mundial: "Corea/Japón 2002", partidos: 64, goles: 161, prom: 2.52, plus25pct: 41 },
    { mundial: "Alemania 2006", partidos: 64, goles: 147, prom: 2.30, plus25pct: 36 },
    { mundial: "Sudáfrica 2010", partidos: 64, goles: 145, prom: 2.27, plus25pct: 35 },
    { mundial: "Brasil 2014", partidos: 64, goles: 171, prom: 2.67, plus25pct: 44 },
    { mundial: "Rusia 2018", partidos: 64, goles: 169, prom: 2.64, plus25pct: 47 },
    { mundial: "Qatar 2022", partidos: 64, goles: 172, prom: 2.69, plus25pct: 48 },
  ],
  result1x2: {
    victoria_local: 47, empate: 22, victoria_visita: 31,
    nota: "Datos agregados 1930-2022 (todos los partidos mundialistas)"
  },
  handicap: [
    { linea: "AH -0.5", cover_fav: 52 },
    { linea: "AH -1.0", cover_fav: 41 },
    { linea: "AH -1.5", cover_fav: 31 },
    { linea: "AH +0.5", cover_debil: 58 },
    { linea: "AH +1.0", cover_debil: 69 },
  ],
  clima_efecto: [
    { tipo: "Calor >30°C", efecto: "Promedio goles −0.3 vs baseline", nota: "Mayor fatiga, más defensivo en 2T" },
    { tipo: "Lluvia Intensa", efecto: "Empates +8% vs baseline", nota: "Canchas pesadas reducen velocidad ofensiva" },
    { tipo: "Viento >40km/h", efecto: "Errores técnicos +12%", nota: "Balón en juego largo domina" },
    { tipo: "Frío <10°C", efecto: "Goles en 1er tiempo +15%", nota: "Menos resistencia, ritmo inicial más alto" },
    { tipo: "Altitud >2000m", efecto: "Equipos locales +18% rendimiento", nota: "Adaptación es clave" },
    { tipo: "Templado 15-25°C", efecto: "Mayor promedio de goles (+0.2)", nota: "Condición óptima para el juego" },
  ]
};

export const MASSEY_RATINGS: Record<string, number> = {
  "Argentina":    2.85, "España":        2.40, "Francia":       2.20,
  "Inglaterra":   1.95, "Brasil":        2.10, "Portugal":      1.90,
  "Países Bajos": 1.80, "Alemania":      1.75, "Bélgica":       1.55,
  "Croacia":      1.50, "Uruguay":       1.45, "Colombia":      1.40,
  "Dinamarca":    1.55, "Suiza":         1.35, "Marruecos":     1.20,
  "Noruega":      1.42, "Estados Unidos":1.30, "México":        1.22,
  "Japón":        1.18, "Senegal":       1.10, "Austria":       1.15,
  "Turquía":      1.05, "Corea del Sur": 1.00, "Ecuador":       0.90,
  "Australia":    0.85, "Suecia":        0.88, "Escocia":       0.92,
  "Irán":         0.75, "Canadá":        0.80, "Paraguay":      0.65,
  "República Checa":0.95,"Egipto":       0.60, "Túnez":         0.55,
  "Costa Rica":   0.50, "Arabia Saudita":0.48, "Ghana":         0.45,
  "Argelia":      0.42, "Costa de Marfil":0.40,"RD Congo":      0.30,
  "Sudáfrica":    0.35, "Irak":          0.20, "Uzbekistán":    0.18,
  "Jordania":     0.15, "Cabo Verde":    0.25, "Panamá":        0.10,
  "Haití":       -0.20, "Curazao":      -0.35, "Nueva Zelanda":-0.45,
  "Catar":       -0.30, "Bosnia y Herzegovina":0.70
};

export const COLLEY_RATINGS: Record<string, number> = {
  "Argentina":    0.895, "España":        0.862, "Francia":       0.848,
  "Inglaterra":   0.830, "Brasil":        0.840, "Portugal":      0.825,
  "Países Bajos": 0.815, "Alemania":      0.808, "Bélgica":       0.790,
  "Croacia":      0.785, "Uruguay":       0.778, "Colombia":      0.772,
  "Dinamarca":    0.788, "Suiza":         0.768, "Marruecos":     0.750,
  "Noruega":      0.774, "Estados Unidos":0.755, "México":        0.748,
  "Japón":        0.745, "Senegal":       0.735, "Austria":       0.742,
  "Turquía":      0.730, "Corea del Sur": 0.725, "Ecuador":       0.715,
  "Australia":    0.708, "Suecia":        0.710, "Escocia":       0.718,
  "Irán":         0.700, "Canadá":        0.705, "Paraguay":      0.692,
  "República Checa":0.720,"Egipto":       0.685, "Túnez":         0.680,
  "Costa Rica":   0.672, "Arabia Saudita":0.668, "Ghana":         0.662,
  "Argelia":      0.658, "Costa de Marfil":0.655,"RD Congo":      0.642,
  "Sudáfrica":    0.648, "Irak":          0.628, "Uzbekistán":    0.625,
  "Jordania":     0.620, "Cabo Verde":    0.635, "Panamá":        0.615,
  "Haití":        0.590, "Curazao":       0.578, "Nueva Zelanda": 0.570,
  "Catar":        0.582, "Bosnia y Herzegovina":0.695
};

export const PI_RATINGS: Record<string, { home: number; away: number }> = {
  "Argentina":    { home: 1.820, away: 1.650 },
  "España":       { home: 1.680, away: 1.510 },
  "Francia":      { home: 1.620, away: 1.480 },
  "Inglaterra":   { home: 1.550, away: 1.380 },
  "Brasil":       { home: 1.600, away: 1.440 },
  "Portugal":     { home: 1.540, away: 1.370 },
  "Países Bajos": { home: 1.480, away: 1.320 },
  "Alemania":     { home: 1.470, away: 1.300 },
  "Bélgica":      { home: 1.380, away: 1.210 },
  "Croacia":      { home: 1.360, away: 1.190 },
  "Uruguay":      { home: 1.340, away: 1.170 },
  "Colombia":     { home: 1.320, away: 1.150 },
  "Dinamarca":    { home: 1.370, away: 1.195 },
  "Suiza":        { home: 1.305, away: 1.140 },
  "Marruecos":    { home: 1.260, away: 1.090 },
  "Noruega":      { home: 1.330, away: 1.155 },
  "Estados Unidos":{ home: 1.285, away: 1.115 },
  "México":       { home: 1.270, away: 1.095 },
  "Japón":        { home: 1.250, away: 1.080 },
  "Senegal":      { home: 1.230, away: 1.060 },
  "Austria":      { home: 1.240, away: 1.070 },
  "Turquía":      { home: 1.215, away: 1.045 },
  "Corea del Sur":{ home: 1.205, away: 1.035 },
  "Ecuador":      { home: 1.180, away: 1.010 },
  "Australia":    { home: 1.170, away: 1.000 },
  "Suecia":       { home: 1.175, away: 1.005 },
  "Escocia":      { home: 1.185, away: 1.015 },
  "Irán":         { home: 1.155, away: 0.985 },
  "Canadá":       { home: 1.162, away: 0.990 },
  "Paraguay":     { home: 1.140, away: 0.970 },
  "República Checa":{ home: 1.195, away: 1.025 },
  "Egipto":       { home: 1.125, away: 0.955 },
  "Túnez":        { home: 1.118, away: 0.948 },
  "Costa Rica":   { home: 1.105, away: 0.935 },
  "Arabia Saudita":{ home: 1.098, away: 0.928 },
  "Ghana":        { home: 1.090, away: 0.920 },
  "Argelia":      { home: 1.082, away: 0.912 },
  "Costa de Marfil":{ home: 1.078, away: 0.908 },
  "RD Congo":     { home: 1.055, away: 0.885 },
  "Sudáfrica":    { home: 1.062, away: 0.892 },
  "Irak":         { home: 1.030, away: 0.860 },
  "Uzbekistán":   { home: 1.025, away: 0.855 },
  "Jordania":     { home: 1.018, away: 0.848 },
  "Cabo Verde":   { home: 1.042, away: 0.872 },
  "Panamá":       { home: 1.010, away: 0.840 },
  "Haití":        { home: 0.965, away: 0.795 },
  "Curazao":      { home: 0.945, away: 0.775 },
  "Nueva Zelanda":{ home: 0.935, away: 0.765 },
  "Catar":        { home: 0.950, away: 0.780 },
  "Bosnia y Herzegovina":{ home: 1.145, away: 0.975 }
};

export const FASE_CONFIG: Record<string, { lambdaMult: number; rho: number; ahMod: number; mcMult: number; desc: string; chips: string[] }> = {
  grupos:  { lambdaMult: 1.00, rho: -0.11, ahMod: 0,     mcMult: 1.0,  desc: '📊 <strong style="color:var(--text)">Fase de Grupos:</strong> Mayor promedio de goles (2.70/partido histórico). Equipos aún frescos, tácticas menos conservadoras. ρ Dixon-Coles estándar = −0.11. Home advantage activo.', chips: ['λ ×1.00', 'ρ −0.11', 'AH std', 'MC ×1.0'] },
  ronda32: { lambdaMult: 0.97, rho: -0.11, ahMod: 0,     mcMult: 1.0,  desc: '🔥 <strong style="color:var(--text)">Ronda de 32 (formato nuevo 2026):</strong> Primera fase eliminatoria con 32 equipos. Equipos de grupos conservan ritmo. Ligero ajuste defensivo (λ ×0.97). Sin prórroga.', chips: ['λ ×0.97', 'ρ −0.11', 'AH std', 'MC ×1.0'] },
  octavos: { lambdaMult: 0.93, rho: -0.09, ahMod: -0.05, mcMult: 1.0,  desc: '🏆 <strong style="color:var(--text)">Octavos de Final:</strong> Equipos más conservadores. Menor tasa de goles (2.40/partido histórico). ρ reducido = −0.09 (menos empates bajos). Probabilidad empate +5%.', chips: ['λ ×0.93', 'ρ −0.09', 'AH −0.05', 'MC ×1.0'] },
  cuartos: { lambdaMult: 0.88, rho: -0.08, ahMod: -0.10, mcMult: 0.95, desc: '⚡ <strong style="color:var(--text)">Cuartos de Final:</strong> Alta intensidad táctica. Promedio goles baja a ~2.25. ρ = −0.08. Más probabilidad de marcar 0-0 real (prórroga histórica 22%). Umbral AH más conservador.', chips: ['λ ×0.88', 'ρ −0.08', 'AH −0.10', 'MC ×0.95'] },
  semis:   { lambdaMult: 0.84, rho: -0.07, ahMod: -0.15, mcMult: 0.90, desc: '🎯 <strong style="color:var(--text)">Semifinales:</strong> Los partidos más tácticos. Promedio goles: ~2.1. ρ = −0.07. Histórico: 28% van a prórroga. Favoritos tienen ventaja significativa. Ambos marcan: 52%.', chips: ['λ ×0.84', 'ρ −0.07', 'AH −0.15', 'MC ×0.90'] },
  final:   { lambdaMult: 0.80, rho: -0.06, ahMod: -0.20, mcMult: 0.85, desc: '👑 <strong style="color:var(--text)">Gran Final:</strong> El partido más cerrado del torneo. Promedio histórico: 2.0 goles. ρ = −0.06 (alta corrección empates bajos). 35% van a prórroga. Usar menos el AH, favorece mercados de goles totales bajos.', chips: ['λ ×0.80', 'ρ −0.06', 'AH −0.20', 'MC ×0.85'] },
};
